### ISSUE TITLE
The "Plan My Program" page needs more explanation

### ISSUE THREAD

**Issue by trystant** [tsehayegh/my-acad-roadmap#3]
![screenshot 2018-06-28 at 06 03 48](https://user-images.githubusercontent.com/13509/42028001-190559c6-7a99-11e8-9977-ea6468e9402c.png)
The average person coming to this page with no exposure to classes or groups has no idea how they relate to each other. Some more explanation on the right side of the page when they land on it would be helpful.

**Comment by trystant** [comment]
Perhaps an animated image of the process that loads with the page.

**Comment by tsehayegh** [comment]
The issue was addressed by adding a note on the right hand side of the page and added a tooltip for the lists on the left.

**Comment by trystant** [comment]
There is more information here. How has user testing gone with this piece?
