### ISSUE TITLE
Add a header to explain the values for each class

### ISSUE THREAD

**Issue by trystant** [tsehayegh/my-acad-roadmap#4]
![screenshot 2018-06-28 at 06 06 43](https://user-images.githubusercontent.com/13509/42028194-9aca903e-7a99-11e8-807d-a65dbaf5be6f.png)
I was able to determine that the last number in this image stands for credits, but the user doesn't know that offhand. Having a header similar to an excel spreadsheet header would be helpful.

**Comment by tsehayegh** [comment]
The issue was addressed by by adding a header at the top of the list.

**Comment by trystant** [comment]
The header is correct, although I was indicating that a color contrast with the header may work better, like 
![screenshot 2018-07-06 at 12 18 14](https://user-images.githubusercontent.com/13509/42389437-b891756e-8116-11e8-9d7f-895e09e8cdf3.png)
