### ISSUE TITLE
Can one take more than the required number of classes from a group?

### ISSUE THREAD

**Issue by trystant** [tsehayegh/my-acad-roadmap#5]
I noticed that while it says to take 1 class from this group, I was able to select 3 classes. Is this correct?
![screenshot 2018-06-28 at 06 11 11](https://user-images.githubusercontent.com/13509/42028386-2702c440-7a9a-11e8-8924-47839d69cf0e.png)

**Comment by tsehayegh** [comment]
I was not able to address the issue. I tried several methods but I was not successful.

**Comment by tsehayegh** [comment]
Issue was addressed. Now, users can not choose more than required courses.

**Comment by trystant** [comment]
I'm assuming that this page is a result of the change, where it says that 1 class can be chosen in green on the left, but 0 can be chosen on the right?
![screenshot 2018-07-06 at 12 16 03](https://user-images.githubusercontent.com/13509/42389357-764a2660-8116-11e8-8da9-53daad6920e0.png)
